export enum EStorageKey {
  USER = "USER",
}

export enum EBackgroundMessage {
  START_DOWNLOAD_USER_POSTS = "START_DOWNLOAD_USER_POSTS",
  ALL_DOWNLOAD_PROGRESS = "ALL_DOWNLOAD_PROGRESS",
  REQUEST_ALL_DOWNLOAD_PROGRESS = "REQUEST_ALL_DOWNLOAD_PROGRESS",
  CANCEL_DOWNLOAD = "CANCEL_DOWNLOAD",
}
